#!/bin/bash

CDIR=$(dirname "$(readlink -f "$0")")
echo "Config directory: " $CDIR

function link {
        echo "linking $1 $2"
        ln -s $1 $2
}

if [[ -z $1 ]]
then
        link $CDIR/gtkrc-2.0.mine ~/.gtkrc-2.0.mine
        link $CDIR/i3/i3pystatus_config.py ~/.i3/i3pystatus_config.py
        link $CDIR/i3/config ~/.i3/config
        link $CDIR/Xmodmap ~/.Xmodmap
        link $CDIR/Xresources ~/.Xresources
        link $CDIR/zshrc ~/.zshrc
        link $CDIR/zprofile ~/.zprofile

        # Vim
        link $CDIR/vim/vimrc ~/.vimrc
        link $CDIR/vim/gvimrc ~/.gvimrc

        link $CDIR/vim/ycm_extra_conf_c.py ~/.config/.ycm_extra_conf_c.py

        link $CDIR/vim/filetype ~/.vim/ftplugin

        link $CDIR/vim/syntax ~/.vim/syntax

        link $CDIR/vim/snippets ~/.vim/mysnippets
fi
